name: Feature Request
description: File a feature request
title: "[Feature]: "
labels: ["Feature", "triage"]
assignees:
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Feature request report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: Suggest an idea for this project ?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Checklist
      multiple: true
      options:
          - I have searched the existing issues to make sure this is not a duplicate
          - I have checked the documentation and found no answer
    validations:
      required: true


  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you using
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true


